# Generated by Django 4.1.7 on 2023-03-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restroapp.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restroapp.customer')),
            ],
        ),
    ]
