# Generated by Django 4.1.7 on 2023-03-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0004_reviewrating_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='user',
            new_name='customer',
        ),
    ]
