# Generated by Django 4.1.7 on 2023-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0006_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
